mysql:
  username: "root"
  password: "123456"
  ip: "localhost"
  port: 3306
  tsxci_daily_db: "tsxci_daily"
  tsxci_intraday_db: 'tsxci_intraday'
gmail:
  username: "XXXX@gmail.com"
  password: "XXXX"
  recipient : "XXXX@gmail.com"
